name: CI Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: db_todo
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for database connection..."
            sleep 3
          done

      - name: Grant execute permission to mvnw
        run: chmod +x mvnw

      - name: Run tests
        run: ./mvnw test

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and Push Docker Image
        run: |
          COMMIT_SHA=${{ github.sha }}
          IMAGE_NAME=salerscl/todo-list-api
          docker build -t $IMAGE_NAME:$COMMIT_SHA .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" |
            docker login -u "salerscl" --password-stdin
          docker push $IMAGE_NAME:$COMMIT_SHA
